# emcmake cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build

CMAKE_MINIMUM_REQUIRED(VERSION 3.10)
PROJECT(slicer)
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_CXX_STANDARD 17)

file(GLOB_RECURSE sources      src/*.cpp src/*.h)
ADD_EXECUTABLE(${PROJECT_NAME} ${sources})

IF(EMSCRIPTEN)
	SET(FILESYSTEM_DIR data)
	SET(FILESYSTEM_OUTPUT files)
	file(GLOB FILESYSTEM_FILES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/${FILESYSTEM_DIR}/ankle.stl")
	file(GLOB_RECURSE PROFILE_FILES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/${FILESYSTEM_DIR}/profiles/*")
	list(APPEND FILESYSTEM_FILES ${PROFILE_FILES})

	set(FILESYSTEM_FILES_RELATIVE "")
	foreach(FILE ${FILESYSTEM_FILES})
		file(RELATIVE_PATH RELATIVE_FILE "${CMAKE_CURRENT_SOURCE_DIR}/${FILESYSTEM_DIR}" "${FILE}")
		list(APPEND FILESYSTEM_FILES_RELATIVE "${RELATIVE_FILE}")
	endforeach()

	SET(PACKAGING_TOOL ${EMSCRIPTEN_ROOT_PATH}/tools/file_packager.py)
	SET(EXTERNAL_FUNCTIONS _slice,_resume,_setLayerDirection,_setLayerFromImage,_getLayerFromImage,_loadLayerImage,_getLayerDirection,_getTriangles,_getTrianglesCount,_getToolpath,_getToolpathCount,_getWaypointCount,_getLayer,_getLayerVertexCount,_getLayerCount,_loadSTL,_getProfileNames,_saveProfile,_free)

	SET_TARGET_PROPERTIES(${PROJECT_NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/server/public")

	ADD_CUSTOM_TARGET(COPY_WEB_FILES ALL
		COMMAND ${CMAKE_COMMAND} -E copy 
		${CMAKE_CURRENT_SOURCE_DIR}/data/favicon.ico
		${CMAKE_CURRENT_SOURCE_DIR}/src/web/index.html
		${CMAKE_CURRENT_SOURCE_DIR}/src/web/app.js
		${CMAKE_CURRENT_SOURCE_DIR}/src/web/gl.js
		${CMAKE_CURRENT_SOURCE_DIR}/src/web/style.css
		${CMAKE_CURRENT_SOURCE_DIR}/server/public
	)
	ADD_DEPENDENCIES(${PROJECT_NAME} COPY_WEB_FILES)

	FIND_PACKAGE(Python)
	ADD_CUSTOM_TARGET(PACKAGE_FILESYSTEM ALL
		COMMAND Python::Interpreter ${PACKAGING_TOOL} ${FILESYSTEM_OUTPUT}.data --preload ${FILESYSTEM_FILES_RELATIVE} --js-output=${FILESYSTEM_OUTPUT}.js --quiet --use-preload-plugins
		COMMAND ${CMAKE_COMMAND} -E copy ${FILESYSTEM_OUTPUT}.data ${FILESYSTEM_OUTPUT}.js ${CMAKE_CURRENT_SOURCE_DIR}/server/public
		COMMAND ${CMAKE_COMMAND} -E rm ${FILESYSTEM_OUTPUT}.data ${FILESYSTEM_OUTPUT}.js
		WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/${FILESYSTEM_DIR}
	)
	ADD_DEPENDENCIES(${PROJECT_NAME} PACKAGE_FILESYSTEM)

	TARGET_LINK_OPTIONS(${PROJECT_NAME} PRIVATE -sFORCE_FILESYSTEM)
	TARGET_LINK_OPTIONS(${PROJECT_NAME} PRIVATE --pre-js ${CMAKE_CURRENT_SOURCE_DIR}/server/public/${FILESYSTEM_OUTPUT}.js)
	TARGET_LINK_OPTIONS(${PROJECT_NAME} PRIVATE -sEXPORTED_FUNCTIONS=${EXTERNAL_FUNCTIONS})
	TARGET_LINK_OPTIONS(${PROJECT_NAME} PRIVATE -sEXPORTED_RUNTIME_METHODS=stringToNewUTF8,HEAPF32)

	TARGET_COMPILE_OPTIONS(${PROJECT_NAME} PRIVATE --target=wasm64)
	TARGET_LINK_OPTIONS(${PROJECT_NAME} PRIVATE --target=wasm64)
	TARGET_LINK_OPTIONS(${PROJECT_NAME} PRIVATE -sALLOW_MEMORY_GROWTH)
	TARGET_LINK_OPTIONS(${PROJECT_NAME} PRIVATE -sMAXIMUM_MEMORY=17179869184)

	TARGET_COMPILE_OPTIONS(${PROJECT_NAME} PRIVATE -pthread)
	TARGET_LINK_OPTIONS(${PROJECT_NAME} PRIVATE -sPTHREAD_POOL_SIZE_STRICT=0)
	TARGET_LINK_OPTIONS(${PROJECT_NAME} PRIVATE -sASSERTIONS)
	TARGET_LINK_OPTIONS(${PROJECT_NAME} PRIVATE -sNO_DISABLE_EXCEPTION_CATCHING)
	TARGET_LINK_OPTIONS(${PROJECT_NAME} PRIVATE -Wno-unused-main)
	TARGET_LINK_OPTIONS(${PROJECT_NAME} PRIVATE -Wno-pthreads-mem-growth)
	TARGET_LINK_OPTIONS(${PROJECT_NAME} PRIVATE -pthread)
	TARGET_LINK_OPTIONS(${PROJECT_NAME} PRIVATE -sPTHREAD_POOL_SIZE=navigator.hardwareConcurrency)
ENDIF()